es.ull.esit.app.Cashier Class Reference
Public Member Functions
Cashier ()
Constructor por defecto.
Cashier (String name)
Constructor con nombre del cajero.
Cashier (es.ull.esit.app.middleware.ApiClient apiClient, String... optionalName)
Constructor que recibe un ApiClient y opcionalmente el nombre del cajero.
Static Public Member Functions
static void main (String args[])
Punto de entrada para ejecutar esta ventana de forma independiente.
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
Acción para abrir la ventana "About us".
void jButton2ActionPerformed (java.awt.event.ActionEvent evt)
void jButton3ActionPerformed (java.awt.event.ActionEvent evt)
Acción para cerrar sesi f3n y volver al login.
Private Attributes
es.ull.esit.app.middleware.ApiClient api
javax.swing.JButton jButton1
javax.swing.JButton jButton2
javax.swing.JButton jButton3
javax.swing.JLabel jLabel1
javax.swing.JPanel jPanel1
javax.swing.JLabel welcomeTxt
Detailed Description
Definition at line 20 of file Cashier.java.
Constructor & Destructor Documentation
Cashier() [1/3]
es.ull.esit.app.Cashier.Cashier () [inline]
Constructor por defecto.
Inicializa la interfaz.
Definition at line 28 of file Cashier.java.
                     {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
Referenced by main().
Cashier() [2/3]
es.ull.esit.app.Cashier.Cashier (String name) [inline]
Constructor con nombre del cajero.
Muestra un mensaje de bienvenida personalizado.
Parameters
name nombre del cajero que inici f3 sesi f3n
Definition at line 38 of file Cashier.java.
                                                {
    // Añadido: cliente para comunicarse con el middleware REST
    private es.ull.esit.app.middleware.ApiClient api;
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
Cashier() [3/3]
es.ull.esit.app.Cashier.Cashier (es.ull.esit.app.middleware.ApiClient apiClient, String... optionalName) [inline]
Constructor que recibe un ApiClient y opcionalmente el nombre del cajero.
Definition at line 45 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References initComponents(), and welcomeTxt.
Member Function Documentation
initComponents()
void es.ull.esit.app.Cashier.initComponents () [inline], [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 63 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References initComponents(), jButton1, jButton2, jButton3, jLabel1, jPanel1, and welcomeTxt.
Referenced by Cashier(), and initComponents().
jButton1ActionPerformed()
void es.ull.esit.app.Cashier.jButton1ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Acción para abrir la ventana "About us".
Parameters
evt evento de acción del botón
Definition at line 176 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References api.
jButton2ActionPerformed()
void es.ull.esit.app.Cashier.jButton2ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Definition at line 193 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References api.
jButton3ActionPerformed()
void es.ull.esit.app.Cashier.jButton3ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Acción para cerrar sesi f3n y volver al login.
Parameters
evt evento de acción del botón
Definition at line 218 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References api.
main()
void es.ull.esit.app.Cashier.main (String args[]) [inline], [static]
Punto de entrada para ejecutar esta ventana de forma independiente.
Parameters
args argumentos de línea de comandos (no se usan)
Definition at line 238 of file Cashier.java.
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
References Cashier().
Member Data Documentation
api
es.ull.esit.app.middleware.ApiClient es.ull.esit.app.Cashier.api [private]
Definition at line 23 of file Cashier.java.
Referenced by jButton1ActionPerformed(), jButton2ActionPerformed(), and jButton3ActionPerformed().
jButton1
javax.swing.JButton es.ull.esit.app.Cashier.jButton1 [private]
Definition at line 271 of file Cashier.java.
Referenced by initComponents().
jButton2
javax.swing.JButton es.ull.esit.app.Cashier.jButton2 [private]
Definition at line 272 of file Cashier.java.
Referenced by initComponents().
jButton3
javax.swing.JButton es.ull.esit.app.Cashier.jButton3 [private]
Definition at line 273 of file Cashier.java.
Referenced by initComponents().
jLabel1
javax.swing.JLabel es.ull.esit.app.Cashier.jLabel1 [private]
Definition at line 274 of file Cashier.java.
Referenced by initComponents().
jPanel1
javax.swing.JPanel es.ull.esit.app.Cashier.jPanel1 [private]
Definition at line 275 of file Cashier.java.
Referenced by initComponents().
welcomeTxt
javax.swing.JLabel es.ull.esit.app.Cashier.welcomeTxt [private]
Definition at line 276 of file Cashier.java.
Referenced by Cashier(), and initComponents().
The documentation for this class was generated from the following file:
Cashier.java