es.ull.esit.app.Info Class Reference
Public Member Functions
Info ()
Creates new form Info.
Static Public Member Functions
static void main (String args[])
Private Member Functions
void initComponents ()
This method is called from within the constructor to initialize the form.
void jButton3ActionPerformed (java.awt.event.ActionEvent evt)
Private Attributes
javax.swing.JButton jButton3
javax.swing.JLabel jLabel1
javax.swing.JPanel jPanel1
javax.swing.JScrollPane jScrollPane1
javax.swing.JTextArea ourStory
Detailed Description
Definition at line 12 of file Info.java.
Constructor & Destructor Documentation
Info()
es.ull.esit.app.Info.Info () [inline]
Creates new form Info.
Definition at line 17 of file Info.java.
References initComponents().
Referenced by main().
Member Function Documentation
initComponents()
void es.ull.esit.app.Info.initComponents () [inline], [private]
This method is called from within the constructor to initialize the form.
WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
Definition at line 28 of file Info.java.
References initComponents(), jButton3, jLabel1, jPanel1, jScrollPane1, and ourStory.
Referenced by Info(), and initComponents().
jButton3ActionPerformed()
void es.ull.esit.app.Info.jButton3ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Definition at line 105 of file Info.java.
main()
void es.ull.esit.app.Info.main (String args[]) [inline], [static]
Parameters
args the command line arguments
Definition at line 113 of file Info.java.
References Info().
Member Data Documentation
jButton3
javax.swing.JButton es.ull.esit.app.Info.jButton3 [private]
Definition at line 146 of file Info.java.
Referenced by initComponents().
jLabel1
javax.swing.JLabel es.ull.esit.app.Info.jLabel1 [private]
Definition at line 147 of file Info.java.
Referenced by initComponents().
jPanel1
javax.swing.JPanel es.ull.esit.app.Info.jPanel1 [private]
Definition at line 148 of file Info.java.
Referenced by initComponents().
jScrollPane1
javax.swing.JScrollPane es.ull.esit.app.Info.jScrollPane1 [private]
Definition at line 149 of file Info.java.
Referenced by initComponents().
ourStory
javax.swing.JTextArea es.ull.esit.app.Info.ourStory [private]
Definition at line 150 of file Info.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
Info.java