/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ull.esit.app;

import java.util.List;

/**
 * @file Cashier.java
 * @brief User interface for the cashier (Cashier).
 *
 * Provides buttons to view information, open the menu and log out. It also
 * includes a client to communicate with the REST middleware (ApiClient) and
 * load remote data asynchronously.
 *
 * @version 1.0
 */
public class Cashier extends javax.swing.JFrame {

    /** @brief HTTP client used to communicate with the REST middleware. */
    private es.ull.esit.app.middleware.ApiClient api;

    /**
     * @brief Default constructor. Initializes the UI.
     */
    public Cashier() {
        this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"));
    }
       /**
        * @brief Constructor that accepts a cashier name.
        *
        * Displays a personalized welcome message.
        *
        * @param name name of the cashier who logged in
        */
       public Cashier(String name) {
           this(new es.ull.esit.app.middleware.ApiClient("http://localhost:8080"), name);
       }

       /**
        * @brief Constructor that receives an ApiClient and optionally the cashier name.
        *
        * If no ApiClient is provided, a default one pointing to localhost is used.
        */
       public Cashier(es.ull.esit.app.middleware.ApiClient apiClient, String... optionalName) {
        initComponents();
        this.api = apiClient == null ? new es.ull.esit.app.middleware.ApiClient("http://localhost:8080") : apiClient;
        String name = (optionalName != null && optionalName.length>0) ? optionalName[0] : null;
        if (name == null || name.isEmpty()) {
            welcomeTxt.setText("Welcome Cashier,");
        } else {
            welcomeTxt.setText("Welcome " + name);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeTxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(248, 244, 230));

        welcomeTxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        welcomeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTxt.setText("Welcome Cashier");

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton1.setText("About us");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            /**
             * @brief Handler for the "About us" button.
             *
             * When pressed, opens the information window (Info).
             *
             * @param evt Action event generated by the button.
             * @return void
             */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton2.setText("Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            /**
             * @brief Handler for the "Menu" button.
             *
             * When pressed, opens the menu window (Frame1).
             *
             * @param evt Action event generated by the button.
             * @return void
             */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jButton3.setText("LogOut");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            /**
             * @brief Handler for the "LogOut" button.
             *
             * When pressed, the current session is closed and the login window
             * (Login) is shown.
             *
             * @param evt Action event generated by the button.
             * @return void
             */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(183, 183, 183))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190)))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(242, 242, 242)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @brief Acción para abrir la ventana "About us".
     *
     * @param evt evento de acción del botón
     */
    // ...existing code...

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // If you want to show cashier info instead of generic info
        new Thread(() -> {
            try {
                // Example: get cashier data
                List<es.ull.esit.app.middleware.model.Cashier> cashiers = api.getAllCashiers();
                System.out.println("Found " + cashiers.size() + " cashiers");
            } catch (Exception ex) {
                System.err.println("Error getting cashiers: " + ex.getMessage());
            }
            javax.swing.SwingUtilities.invokeLater(() -> {
                new Info().setVisible(true);
                dispose();
            });
        }).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Load menu items using new CRUD methods
        new Thread(() -> {
            try {
                List<es.ull.esit.app.middleware.model.Appetizer> appetizers = api.getAllAppetizers();
                List<es.ull.esit.app.middleware.model.Drink> drinks = api.getAllDrinks();
                List<es.ull.esit.app.middleware.model.MainCourse> mainCourses = api.getAllMainCourses();
                
                System.out.println("Menu loaded: " + appetizers.size() + " appetizers, " + 
                                 drinks.size() + " drinks, " + mainCourses.size() + " main courses");
            } catch (Exception ex) {
                System.err.println("Error loading menu: " + ex.getMessage());
            }
            javax.swing.SwingUtilities.invokeLater(() -> {
                new Frame1().setVisible(true);
                dispose();
            });
        }).start();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @brief Acción para cerrar sesión y volver al login.
     *
     * @param evt evento de acción del botón
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Opcional: notificar al middleware del logout
        new Thread(() -> {
            // No client logout method available on ApiClient; skip remote logout.
            javax.swing.SwingUtilities.invokeLater(() -> {
                new Login().setVisible(true);
                dispose();
            });
        }).start();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @brief Punto de entrada para ejecutar esta ventana de forma independiente.
     *
     * @param args argumentos de línea de comandos (no se usan)
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** @brief Botón "About us" para ver información del restaurante. */
    private javax.swing.JButton jButton1;
    /** @brief Botón para abrir el menú (Frame1). */
    private javax.swing.JButton jButton2;
    /** @brief Botón para cerrar sesión (LogOut). */
    private javax.swing.JButton jButton3;
    /** @brief Imagen/logo mostrado en la ventana. */
    private javax.swing.JLabel jLabel1;
    /** @brief Panel contenedor principal. */
    private javax.swing.JPanel jPanel1;
    /** @brief Etiqueta para mostrar el texto de bienvenida al cajero. */
    private javax.swing.JLabel welcomeTxt;
    // End of variables declaration//GEN-END:variables
}
