package es.ull.esit.server.middleware.model;

import javax.persistence.*;

/**
 * @brief JPA entity that represents an appetizer in the menu.
 *
 *        It is mapped to the "appetizers" table used by the REST API. 
 *        Each record has an auto-increment ID, a name and a price.
 */
@Entity
@Table(name = "appetizers")
public class Appetizer {

  /** Primary key of the appetizer (column "id"). */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Long appetizersId;

  /** Name of the appetizer (column "name"). */
  @Column(name = "name", nullable = false)
  private String itemAppetizers;

  /** Price of the appetizer (column "price"). */
  @Column(name = "price", nullable = false)
  private Integer appetizersPrice;

  /** 
   * @brief Default constructor required by JPA. 
   */
  public Appetizer() {
  }

  /** 
   * @brief Full constructor.
   *
   * @param appetizersId    [Long] Identifier of the appetizer.
   * @param itemAppetizers  [String] Name of the appetizer.
   * @param appetizersPrice [Integer] Price of the appetizer.
   */
  public Appetizer(Long appetizersId, String itemAppetizers, Integer appetizersPrice) {
    this.appetizersId = appetizersId;
    this.itemAppetizers = itemAppetizers;
    this.appetizersPrice = appetizersPrice;
  }

  /** 
   * @brief Gets the appetizer ID.
   * 
   * @return [Long] Appetizer id.
   */
  public Long getAppetizersId() {
    return appetizersId;
  }

  /** 
   * @brief Sets the appetizer ID.
   * 
   *        Generated by the database.
   * @param appetizersId [Long] Appetizer id.
   */
  public void setAppetizersId(Long appetizersId) {
    this.appetizersId = appetizersId;
  }

  /**
   * @brief Gets the appetizer name.
   * 
   * @return [String] Appetizer name.
   */
  public String getItemAppetizers() {
    return itemAppetizers;
  }

  /** 
   * @brief Sets the appetizer name.
   * 
   * @param itemAppetizers [String] Appetizer name.
   */
  public void setItemAppetizers(String itemAppetizers) {
    this.itemAppetizers = itemAppetizers;
  }

  /**
   * @brief Gets the appetizer price.
   * 
   * @return [Integer] Appetizer price.
   */
  public Integer getAppetizersPrice() {
    return appetizersPrice;
  }

  /** 
   * @brief Sets the appetizer price.
   * 
   * @param appetizersPrice [Integer] Appetizer price.
   */
  public void setAppetizersPrice(Integer appetizersPrice) {
    this.appetizersPrice = appetizersPrice;
  }
}
