package es.ull.esit.server.middleware.model;

import javax.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * @brief JPA entity that represents a drink in the menu.
 *
 *        It is mapped to the "drinks" table used by the REST API.
 *        Each row contains an auto generated identifier, a name and a price.
 */
@Entity
@Table(name = "drinks")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Drink {

  /** Primary key of the drink (column "id"). */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Long drinksId;

  /** Name of the drink (column "name"). */
  @Column(name = "name", nullable = false)
  private String itemDrinks;

  /** Price of the drink in integer units (column "price"). */
  @Column(name = "price", nullable = false)
  private Integer drinksPrice;

  /**
   * @brief Default constructor required by JPA.
   */
  public Drink() {
  }

  /**
   * @brief Full constructor.
   *
   * @param drinksId    [Long] Identifier of the drink.
   * @param itemDrinks  [String] Name of the drink.
   * @param drinksPrice [Integer] Price of the drink.
   */
  public Drink(Long drinksId, String itemDrinks, Integer drinksPrice) {
    this.drinksId = drinksId;
    this.itemDrinks = itemDrinks;
    this.drinksPrice = drinksPrice;
  }

  /**
   * @brief Gets the drink identifier.
   *
   * @return [Long] Drink id.
   */
  public Long getDrinksId() {
    return drinksId;
  }

  /**
   * @brief Sets the drink identifier.
   *
   *        Generated by the database.
   *
   * @param drinksId [Long] Drink id.
   */
  public void setDrinksId(Long drinksId) {
    this.drinksId = drinksId;
  }

  /**
   * @brief Gets the drink name.
   *
   * @return [String] Drink name.
   */
  public String getItemDrinks() {
    return itemDrinks;
  }

  /**
   * @brief Sets the drink name.
   *
   * @param itemDrinks [String] New name of the drink.
   */
  public void setItemDrinks(String itemDrinks) {
    this.itemDrinks = itemDrinks;
  }

  /**
   * @brief Gets the drink price.
   *
   * @return [Integer] Drink price.
   */
  public Integer getDrinksPrice() {
    return drinksPrice;
  }

  /**
   * @brief Sets the drink price.
   *
   * @param drinksPrice [Integer] New price of the drink.
   */
  public void setDrinksPrice(Integer drinksPrice) {
    this.drinksPrice = drinksPrice;
  }
}
