package es.ull.esit.server.middleware.model;

import javax.persistence.*;

/**
 * @brief JPA entity that represents a main course in the menu.
 *
 *       It is mapped to the "maincourse" table used by the REST API. 
 *       Each record has an auto-increment ID, a name and a price.
 */
@Entity
@Table(name = "maincourse")
public class MainCourse {

  /** Primary key of the main course (column "id"). */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  private Long foodId;

  /** Name of the main course (column "name"). */
  @Column(name = "name", nullable = false)
  private String itemFood;

  /** Price of the main course (column "price"). */
  @Column(name = "price", nullable = false)
  private Integer foodPrice;

  /** 
   * @brief Default constructor required by JPA. 
   */
  public MainCourse() {
  }

  /** 
   * @brief Full constructor.
   * 
   * @param foodId    [Long] Identifier of the main course.
   * @param itemFood  [String] Name of the main course.
   * @param foodPrice [Integer] Price of the main course.
   */
  public MainCourse(Long foodId, String itemFood, Integer foodPrice) {
    this.foodId = foodId;
    this.itemFood = itemFood;
    this.foodPrice = foodPrice;
  }

  /** 
   * @brief Gets the main course ID.
   * 
   * * @return [Long] Main course id.
   */
  public Long getFoodId() {
    return foodId;
  }

  /** 
   * @brief Sets the main course ID.
   * 
   *        Generated by the database.
   * 
   * @param foodId [Long] Main course id.
   */
  public void setFoodId(Long foodId) {
    this.foodId = foodId;
  }

  /** 
   * @brief Gets the main course name.
   * 
   * @return [String] Main course name.
   */
  public String getItemFood() {
    return itemFood;
  }

  /** 
   * @brief Sets the main course name.
   * 
   * @param itemFood [String] Main course name.
   */
  public void setItemFood(String itemFood) {
    this.itemFood = itemFood;
  }

  /**
   * @brief Gets the main course price.
   * 
   * @return [Integer] Main course price.
   */
  public Integer getFoodPrice() {
    return foodPrice;
  }

  /** 
   * @brief Sets the main course price.
   * 
   * @param foodPrice [Integer] Main course price.
   */
  public void setFoodPrice(Integer foodPrice) {
    this.foodPrice = foodPrice;
  }
}
