es.ull.esit.server.controller.DrinkController Class Reference
REST controller for managing drinks.
Public Member Functions
ResponseEntity< List< Drink > > getAllDrinks ()
Returns the complete list of drinks.
ResponseEntity< Drink > getDrinkById (@PathVariable Long id)
Returns a single drink by its id.
ResponseEntity< Drink > createDrink (@RequestBody Drink drink)
Creates a new drink.
ResponseEntity< Drink > updateDrink (@PathVariable Long id, @RequestBody Drink drink)
Updates an existing drink.
ResponseEntity< Void > deleteDrink (@PathVariable Long id)
Deletes a drink by its id.
Private Attributes
DrinkRepository drinkRepository
Repository used to access the "drinks" table.
Detailed Description
REST controller for managing drinks.
   Provides CRUD operations for Drink entities using the path
   "/api/drinks". These endpoints are used by the Swing client to load
   and modify drink information.
Definition at line 22 of file DrinkController.java.
Member Function Documentation
createDrink()
ResponseEntity< Drink > es.ull.esit.server.controller.DrinkController.createDrink (@RequestBody Drink drink) [inline]
Creates a new drink.
   HTTP POST /api/drinks
Parameters
drink [Drink] Drink data sent in the request body.
Returns
[ResponseEntity<Drink>] The created drink with status 201.
Definition at line 65 of file DrinkController.java.
                                                                     {
    Drink saved = drinkRepository.save(drink);
    return ResponseEntity.status(HttpStatus.CREATED).body(saved);
  }
References drinkRepository.
deleteDrink()
ResponseEntity< Void > es.ull.esit.server.controller.DrinkController.deleteDrink (@PathVariable Long id) [inline]
Deletes a drink by its id.
   HTTP DELETE /api/drinks/{id}
Parameters
id [Long] Identifier of the drink to delete.
Returns
[ResponseEntity<Void>] 204 if deleted or 404 if not found.
Definition at line 99 of file DrinkController.java.
                                                                 {
    if (!drinkRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    drinkRepository.deleteById(id);
    return ResponseEntity.noContent().build();
  }
References deleteDrink(), and drinkRepository.
Referenced by deleteDrink().
getAllDrinks()
ResponseEntity< List< Drink > > es.ull.esit.server.controller.DrinkController.getAllDrinks () [inline]
Returns the complete list of drinks.
   HTTP GET /api/drinks
Returns
[ResponseEntity<List<Drink>>] List of drinks with status 200.
Definition at line 36 of file DrinkController.java.
                                                    {
    List<Drink> drinks = drinkRepository.findAll();
    return ResponseEntity.ok(drinks);
  }
References drinkRepository.
getDrinkById()
ResponseEntity< Drink > es.ull.esit.server.controller.DrinkController.getDrinkById (@PathVariable Long id) [inline]
Returns a single drink by its id.
   HTTP GET /api/drinks/{id}
Parameters
id [Long] Identifier of the drink.
Returns
[ResponseEntity<Drink>] The drink if found or 404 otherwise.
Definition at line 50 of file DrinkController.java.
                                                                   {
    Optional<Drink> drink = drinkRepository.findById(id);
    return drink.map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
  }
References drinkRepository, and getDrinkById().
Referenced by getDrinkById().
updateDrink()
ResponseEntity< Drink > es.ull.esit.server.controller.DrinkController.updateDrink (@PathVariable Long id, @RequestBody Drink drink) [inline]
Updates an existing drink.
   HTTP PUT /api/drinks/{id}
Parameters
id [Long] Identifier of the drink to update.
drink [Drink] New data for the drink.
Returns
[ResponseEntity<Drink>] The updated drink or 404 if not found.
Definition at line 80 of file DrinkController.java.
                                {
    if (!drinkRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    drink.setDrinksId(id);
    Drink updated = drinkRepository.save(drink);
    return ResponseEntity.ok(updated);
  }
References drinkRepository, and updateDrink().
Referenced by updateDrink().
Member Data Documentation
drinkRepository
DrinkRepository es.ull.esit.server.controller.DrinkController.drinkRepository [private]
Repository used to access the "drinks" table.
Definition at line 26 of file DrinkController.java.
Referenced by createDrink(), deleteDrink(), getAllDrinks(), getDrinkById(), and updateDrink().
The documentation for this class was generated from the following file:
DrinkController.java