es.ull.esit.server.controller.AppetizerController Class Reference
REST controller for managing appetizers.
Public Member Functions
ResponseEntity< List< Appetizer > > getAllAppetizers ()
Returns the complete list of appetizers.
ResponseEntity< Appetizer > getAppetizerById (@PathVariable Long id)
Returns a single appetizer by its id.
ResponseEntity< Appetizer > createAppetizer (@RequestBody Appetizer appetizer)
Creates a new appetizer.
ResponseEntity< Appetizer > updateAppetizer (@PathVariable Long id, @RequestBody Appetizer appetizer)
Updates an existing appetizer.
ResponseEntity< Void > deleteAppetizer (@PathVariable Long id)
Deletes an appetizer by its id.
Private Attributes
AppetizerRepository appetizerRepository
Repository used to perform database operations on appetizers.
Detailed Description
REST controller for managing appetizers.
Rovides CRUD operations for Appetizer entities using the path "/api/appetizers". These endpoints are used by the Swing client to load and modify appetizer information.
Definition at line 21 of file AppetizerController.java.
Member Function Documentation
createAppetizer()
ResponseEntity< Appetizer > es.ull.esit.server.controller.AppetizerController.createAppetizer (@RequestBody Appetizer appetizer) [inline]
Creates a new appetizer.
   HTTP POST /api/appetizers
Parameters
appetizer [Appetizer] Appetizer to create.
Returns
[ResponseEntity<Appetizer>] The created appetizer with status 201.
Definition at line 65 of file AppetizerController.java.
                                                                                     {
    Appetizer saved = appetizerRepository.save(appetizer);
    return ResponseEntity.status(HttpStatus.CREATED).body(saved);
  }
References appetizerRepository.
deleteAppetizer()
ResponseEntity< Void > es.ull.esit.server.controller.AppetizerController.deleteAppetizer (@PathVariable Long id) [inline]
Deletes an appetizer by its id.
   HTTP DELETE /api/appetizers/{id}
Parameters
id [Long] Identifier of the appetizer to delete.
Returns
[ResponseEntity<Void>] 204 if deleted or 404 if not found.
Definition at line 99 of file AppetizerController.java.
                                                                     {
    if (!appetizerRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    appetizerRepository.deleteById(id);
    return ResponseEntity.noContent().build();
  }
References appetizerRepository, and deleteAppetizer().
Referenced by deleteAppetizer().
getAllAppetizers()
ResponseEntity< List< Appetizer > > es.ull.esit.server.controller.AppetizerController.getAllAppetizers () [inline]
Returns the complete list of appetizers.
   HTTP GET /api/appetizers
Returns
[ResponseEntity<List<Appetizer>>] List of appetizers with status 200.
Definition at line 35 of file AppetizerController.java.
                                                            {
    List<Appetizer> appetizers = appetizerRepository.findAll();
    return ResponseEntity.ok(appetizers);
  }
References appetizerRepository.
getAppetizerById()
ResponseEntity< Appetizer > es.ull.esit.server.controller.AppetizerController.getAppetizerById (@PathVariable Long id) [inline]
Returns a single appetizer by its id.
   HTTP GET /api/appetizers/{id}
Parameters
id [Long] Identifier of the appetizer.
Returns
[ResponseEntity<Appetizer>] The appetizer if found or 404 otherwise.
Definition at line 49 of file AppetizerController.java.
                                                                           {
    Optional<Appetizer> appetizer = appetizerRepository.findById(id);
    return appetizer
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
  }
References appetizerRepository, and getAppetizerById().
Referenced by getAppetizerById().
updateAppetizer()
ResponseEntity< Appetizer > es.ull.esit.server.controller.AppetizerController.updateAppetizer (@PathVariable Long id, @RequestBody Appetizer appetizer) [inline]
Updates an existing appetizer.
   HTTP PUT /api/appetizers/{id}
Parameters
id [Long] Identifier of the appetizer to update.
appetizer [Appetizer] Updated appetizer data.
Returns
[ResponseEntity<Appetizer>] The updated appetizer or 404 if not found.
Definition at line 80 of file AppetizerController.java.
                                                                                     {
    if (!appetizerRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    appetizer.setAppetizersId(id);
    Appetizer updated = appetizerRepository.save(appetizer);
    return ResponseEntity.ok(updated);
  }
References appetizerRepository, and updateAppetizer().
Referenced by updateAppetizer().
Member Data Documentation
appetizerRepository
AppetizerRepository es.ull.esit.server.controller.AppetizerController.appetizerRepository [private]
Repository used to perform database operations on appetizers.
Definition at line 25 of file AppetizerController.java.
Referenced by createAppetizer(), deleteAppetizer(), getAllAppetizers(), getAppetizerById(), and updateAppetizer().
The documentation for this class was generated from the following file:
AppetizerController.java