es.ull.esit.app.Login Class Reference
Login window for the Restaurant System.
Classes
interface MessageDialog
Public Member Functions
Login ()
Constructor.
Static Public Member Functions
static void main (String[] args)
Main entry point to start the login window application.
Private Member Functions
void initComponents ()
Initializes GUI components.
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "Log In" button.
void usertypecmboActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the user type combo box.
Private Attributes
final transient AuthService authService
Service to handle authentication logic.
javax.swing.JButton jButton1
Button to perform login ("Log In").
javax.swing.JLabel jLabel1
Label for the image/logo.
javax.swing.JLabel jLabel3
Label for the title ("User Login").
javax.swing.JPanel jPanel1
Main panel container.
javax.swing.JPasswordField jPasswordField1
Input field for the password.
javax.swing.JTextField usernametxt
Input field for the username.
javax.swing.JComboBox< String > usertypecmbo
Combo box for user type (admin/cashier).
Static Private Attributes
static final String PRIMARY_FONT = "Yu Gothic UI"
Primary font used in the GUI.
static final String LOGIN_STRING = "Log in"
String constant for "Log in" button text.
static java.util.function.Supplier< Login > loginFactory = Login::new
Detailed Description
Login window for the Restaurant System.
   Shows a Swing form that lets the user:
   - enter his/her/their username.
   - enter his/her/their password.
   - select user type (admin or cashier) from a combo box.
   - click the "Log In" button to authenticate.

   The credentials are sent to the backend through AuthService and
   ApiClient.
   According to the role returned by the server (ADMIN or CASHIER), the
   application opens the corresponding window: AdminLogin or Cashier.
Definition at line 23 of file Login.java.
Constructor & Destructor Documentation
Login()
es.ull.esit.app.Login.Login () [inline]
Constructor.
Creates the login window, initializes the AuthService and GUI components.
The ApiClient is configured to connect to the backend at "http://localhost:8080", which must match the URL of the Spring Boot backend server.
Definition at line 78 of file Login.java.
                 {
    initComponents();
    ApiClient client = new ApiClient("http://localhost:8080");
    this.authService = new AuthService(client);
  }
References initComponents().
Referenced by main().
Member Function Documentation
initComponents()
void es.ull.esit.app.Login.initComponents () [inline], [private]
Initializes GUI components.
   Generated by the Form Editor: do not modify.
   Sets up logo image, main label, input fields for username and password, combo box for user type, and button for "Log In", along with the layout and configuration of the window.
Definition at line 92 of file Login.java.
                                {
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    usernametxt = new javax.swing.JTextField();
    usertypecmbo = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jPasswordField1 = new javax.swing.JPasswordField();
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");
    setResizable(false);
    jPanel1.setBackground(new java.awt.Color(248, 244, 230));
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N
    jLabel3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("User Login ");
    usernametxt.setFont(new java.awt.Font(PRIMARY_FONT, 0, 18)); // NOI18N
    usernametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    usernametxt.setBorder(javax.swing.BorderFactory.createTitledBorder(
        new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Username",
        javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font(PRIMARY_FONT, 0, 18))); // NOI18N
    usertypecmbo.setEditable(true);
    usertypecmbo.setFont(new java.awt.Font(PRIMARY_FONT, 0, 18)); // NOI18N
    usertypecmbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "cashier" }));
    usertypecmbo.addActionListener(this::usertypecmboActionPerformed);
    jButton1.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton1.setText(LOGIN_STRING);
    jButton1.addActionListener(this::jButton1ActionPerformed);
    jPasswordField1.setFont(new java.awt.Font("Thonburi", 0, 18)); // NOI18N
    jPasswordField1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Password",
        javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("Lucida Grande", 0, 18))); // NOI18N
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 309,
                            javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usertypecmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 311,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usertypecmbo, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE)));
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents
References initComponents(), jButton1, jLabel1, jLabel3, jPanel1, jPasswordField1, LOGIN_STRING, PRIMARY_FONT, usernametxt, and usertypecmbo.
Referenced by initComponents(), and Login().
jButton1ActionPerformed()
void es.ull.esit.app.Login.jButton1ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "Log In" button.
   Action steps:
   1. Read username and password from the fields.
   2. Disable the button and show "Loading..." to avoid double clicks.
   3. Run authentication in a background thread.
   4. On success, open the admin or cashier window depending on the role.
   5. On error, show a dialog and re-enable the button.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 214 of file Login.java.
                                                                       {// GEN-FIRST:event_jButton1ActionPerformed
    // Get username and password from input fields.
    String usernameInput = usernametxt.getText();
    String passwordInput = new String(jPasswordField1.getPassword());
    jButton1.setEnabled(false);
    jButton1.setText("Loading...");
    new Thread(() -> {
      try {
        // Authenticate user through AuthService.
        User loggedInUser = authService.authenticate(usernameInput, passwordInput);
        SwingUtilities.invokeLater(() -> {
          // Open the corresponding window based on user role. Use the
          // injectable factories so tests can substitute frames.
          if ("ADMIN".equalsIgnoreCase(loggedInUser.getRole())) {
            adminSupplier.get().setVisible(true);
          } else if ("CASHIER".equalsIgnoreCase(loggedInUser.getRole())) {
            cashierFactory.apply(loggedInUser.getUsername()).setVisible(true);
          } else {
            messageDialog.showMessage(this, "Unknown Role: " + loggedInUser.getRole());
            jButton1.setEnabled(true);
            jButton1.setText(LOGIN_STRING);
            return;
          }
          this.dispose();
        });
      } catch (Exception e) {
        SwingUtilities.invokeLater(() -> {
          messageDialog.showMessage(this, "Login failed: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
          jButton1.setEnabled(true);
          jButton1.setText(LOGIN_STRING);
        });
      }
    }).start();
  }// GEN-LAST:event_jButton1ActionPerformed
References authService, es.ull.esit.app.middleware.model.User.getRole(), es.ull.esit.app.middleware.model.User.getUsername(), jButton1, jPasswordField1, LOGIN_STRING, and usernametxt.
main()
void es.ull.esit.app.Login.main (String[] args) [inline], [static]
Main entry point to start the login window application.
Parameters
args [String[]] Command line arguments (not used).
Definition at line 273 of file Login.java.
                                         {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    java.awt.EventQueue.invokeLater(() -> getLoginFactory().get().setVisible(true));
  }
References Login().
usertypecmboActionPerformed()
void es.ull.esit.app.Login.usertypecmboActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the user type combo box.
   The selection is not used in this implementation, as the role is
   determined by the server.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by combo box selection.
Definition at line 264 of file Login.java.
                                                                           {// GEN-FIRST:event_usertypecmboActionPerformed
    // No action needed here.
  }// GEN-LAST:event_usertypecmboActionPerformed
Member Data Documentation
authService
final transient AuthService es.ull.esit.app.Login.authService [private]
Service to handle authentication logic.
Definition at line 26 of file Login.java.
Referenced by jButton1ActionPerformed().
jButton1
javax.swing.JButton es.ull.esit.app.Login.jButton1 [private]
Button to perform login ("Log In").
Definition at line 304 of file Login.java.
Referenced by initComponents(), and jButton1ActionPerformed().
jLabel1
javax.swing.JLabel es.ull.esit.app.Login.jLabel1 [private]
Label for the image/logo.
Definition at line 306 of file Login.java.
Referenced by initComponents().
jLabel3
javax.swing.JLabel es.ull.esit.app.Login.jLabel3 [private]
Label for the title ("User Login").
Definition at line 308 of file Login.java.
Referenced by initComponents().
jPanel1
javax.swing.JPanel es.ull.esit.app.Login.jPanel1 [private]
Main panel container.
Definition at line 310 of file Login.java.
Referenced by initComponents().
jPasswordField1
javax.swing.JPasswordField es.ull.esit.app.Login.jPasswordField1 [private]
Input field for the password.
Definition at line 312 of file Login.java.
Referenced by initComponents(), and jButton1ActionPerformed().
LOGIN_STRING
final String es.ull.esit.app.Login.LOGIN_STRING = "Log in" [static], [private]
String constant for "Log in" button text.
Definition at line 67 of file Login.java.
Referenced by initComponents(), and jButton1ActionPerformed().
loginFactory
java.util.function.Supplier<Login> es.ull.esit.app.Login.loginFactory = Login::new [static], [private]
Definition at line 290 of file Login.java.
PRIMARY_FONT
final String es.ull.esit.app.Login.PRIMARY_FONT = "Yu Gothic UI" [static], [private]
Primary font used in the GUI.
Definition at line 64 of file Login.java.
Referenced by initComponents().
usernametxt
javax.swing.JTextField es.ull.esit.app.Login.usernametxt [private]
Input field for the username.
Definition at line 314 of file Login.java.
Referenced by initComponents(), and jButton1ActionPerformed().
usertypecmbo
javax.swing.JComboBox<String> es.ull.esit.app.Login.usertypecmbo [private]
Combo box for user type (admin/cashier).
Currently not trusted for security decisions.
Definition at line 319 of file Login.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
Login.java