es.ull.esit.app.AdminLogin Class Reference
Login window for authenticating administrators.
Public Member Functions
AdminLogin ()
Constructor.
Static Public Member Functions
static void main (String[] args)
Standalone entry point for testing the AdminLogin window.
Private Member Functions
void initComponents ()
Initializes GUI components.
void jButton2ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "Update Prices" button.
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "Menu" button.
void jButton3ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "LogOut" button.
Private Attributes
javax.swing.JButton jButton1
Button that opens the main menu window.
javax.swing.JButton jButton2
Button that opens the price management window.
javax.swing.JButton jButton3
Button used to log out and return to the login screen.
javax.swing.JLabel jLabel1
Label that displays the application logo or image.
javax.swing.JLabel jLabel3
Label that displays the welcome text for the administrator.
javax.swing.JPanel jPanel1
Main container panel for all UI elements.
Static Private Attributes
static final String PRIMARY_FONT = "Yu Gothic UI"
Primary font used in the UI components.
static final Logger LOGGER = LoggerFactory.getLogger(AdminLogin.class)
Logger for the class.
Detailed Description
Login window for authenticating administrators.
   It is displayed after a successful login with role ADMIN.
   Shows a Swing form that lets administrators:
   - access to the product and price management window.
   - access to the general menu window used to place orders.
   - log out and return to the login window.
Definition at line 16 of file AdminLogin.java.
Constructor & Destructor Documentation
AdminLogin()
es.ull.esit.app.AdminLogin.AdminLogin () [inline]
Constructor.
   Creates the admin login window and initializes GUI components.
Definition at line 38 of file AdminLogin.java.
                      {
    initComponents();
  }
References initComponents().
Referenced by main().
Member Function Documentation
initComponents()
void es.ull.esit.app.AdminLogin.initComponents () [inline], [private]
Initializes GUI components.
   Generated by the Form Editor: do not modify.
   Sets up welcome label, logo image, buttons for "Update Prices",
   "Menu", and "LogOut" and the layout and configuration of the window.
Definition at line 51 of file AdminLogin.java.
                                {
    jPanel1 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jButton2 = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Admin ");
    setResizable(false);
    jPanel1.setBackground(new java.awt.Color(248, 244, 230));
    jLabel3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Welcome Admin");
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N
    jButton2.setBackground(new java.awt.Color(153, 153, 153));
    jButton2.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton2.setText("Update Prices");
    jButton2.addActionListener(this::jButton2ActionPerformed);
    jButton1.setBackground(new java.awt.Color(153, 153, 153));
    jButton1.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton1.setText("Menu");
    jButton1.addActionListener(this::jButton1ActionPerformed);
    jButton3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton3.setText("LogOut");
    jButton3.addActionListener(this::jButton3ActionPerformed);
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 306,
                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                            javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE)));
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents
References initComponents(), jButton1, jButton2, jButton3, jLabel1, jLabel3, jPanel1, and PRIMARY_FONT.
Referenced by AdminLogin(), and initComponents().
jButton1ActionPerformed()
void es.ull.esit.app.AdminLogin.jButton1ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "Menu" button.
Actions steps:
Opens the general menu window to place orders.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 176 of file AdminLogin.java.
                                                                       {// GEN-FIRST:event_jButton1ActionPerformed
  try {
    orderSupplier.get().setVisible(true);
    this.dispose();
  } catch (Exception ex) {
        LOGGER.error("Error opening menu window", ex);
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error opening menu window:\n" + ex.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
  }// GEN-LAST:event_jButton1ActionPerformed
References LOGGER.
jButton2ActionPerformed()
void es.ull.esit.app.AdminLogin.jButton2ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "Update Prices" button.
   Actions steps:
   - Opens the product administration window to modify prices and
   products.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 153 of file AdminLogin.java.
                                                                       {// GEN-FIRST:event_jButton2ActionPerformed
  try {
    adminProductsSupplier.get().setVisible(true);
    this.dispose();
  } catch (Exception ex) {
        LOGGER.error("Error opening product admin window", ex);
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error opening product admin window:\n" + ex.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
  }// GEN-LAST:event_jButton2ActionPerformed
References LOGGER.
jButton3ActionPerformed()
void es.ull.esit.app.AdminLogin.jButton3ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "LogOut" button.
Actions steps:
Logs out the admin and returns to the login window.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 199 of file AdminLogin.java.
                                                                       {// GEN-FIRST:event_jButton3ActionPerformed
  loginSupplier.get().setVisible(true);
  this.dispose();
  }// GEN-LAST:event_jButton3ActionPerformed
main()
void es.ull.esit.app.AdminLogin.main (String[] args) [inline], [static]
Standalone entry point for testing the AdminLogin window.
   Sets the Nimbus look and feel if available and shows an instance
   of AdminLogin. In the normal application flow this window is started
   from the Login class after a successful admin login.
Parameters
args [String[]] Command line arguments (not used).
Definition at line 213 of file AdminLogin.java.
                                         {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>
    java.awt.EventQueue.invokeLater(() -> new AdminLogin().setVisible(true));
  }
References AdminLogin().
Member Data Documentation
jButton1
javax.swing.JButton es.ull.esit.app.AdminLogin.jButton1 [private]
Button that opens the main menu window.
Definition at line 234 of file AdminLogin.java.
Referenced by initComponents().
jButton2
javax.swing.JButton es.ull.esit.app.AdminLogin.jButton2 [private]
Button that opens the price management window.
Definition at line 236 of file AdminLogin.java.
Referenced by initComponents().
jButton3
javax.swing.JButton es.ull.esit.app.AdminLogin.jButton3 [private]
Button used to log out and return to the login screen.
Definition at line 238 of file AdminLogin.java.
Referenced by initComponents().
jLabel1
javax.swing.JLabel es.ull.esit.app.AdminLogin.jLabel1 [private]
Label that displays the application logo or image.
Definition at line 240 of file AdminLogin.java.
Referenced by initComponents().
jLabel3
javax.swing.JLabel es.ull.esit.app.AdminLogin.jLabel3 [private]
Label that displays the welcome text for the administrator.
Definition at line 242 of file AdminLogin.java.
Referenced by initComponents().
jPanel1
javax.swing.JPanel es.ull.esit.app.AdminLogin.jPanel1 [private]
Main container panel for all UI elements.
Definition at line 244 of file AdminLogin.java.
Referenced by initComponents().
LOGGER
final Logger es.ull.esit.app.AdminLogin.LOGGER = LoggerFactory.getLogger(AdminLogin.class) [static], [private]
Logger for the class.
Replaces use of printStackTrace for production-safe logging.
Definition at line 22 of file AdminLogin.java.
Referenced by jButton1ActionPerformed(), and jButton2ActionPerformed().
PRIMARY_FONT
final String es.ull.esit.app.AdminLogin.PRIMARY_FONT = "Yu Gothic UI" [static], [private]
Primary font used in the UI components.
Definition at line 19 of file AdminLogin.java.
Referenced by initComponents().
The documentation for this class was generated from the following file:
AdminLogin.java