es.ull.esit.server.controller.HealthController Class Reference
REST controller for health and database connectivity checks.
Public Member Functions
ResponseEntity< Map< String, Object > > health ()
Basic health endpoint.
ResponseEntity< Map< String, Object > > checkDatabase ()
Database connectivity check.
Private Attributes
DataSource dataSource
DataSource used to verify connectivity with the database.
Detailed Description
REST controller for health and database connectivity checks.
   Exposes simple diagnostic endpoints to:
   - receive basic service liveness information.
   - check connectivity with the underlying database.
   Not required by the Swing frontend but are very
   useful for debugging, monitoring or for external tools that need to
   verify that the service and the database are up and running.
Definition at line 27 of file HealthController.java.
Member Function Documentation
checkDatabase()
ResponseEntity< Map< String, Object > > es.ull.esit.server.controller.HealthController.checkDatabase () [inline]
Database connectivity check.
   Endpoint: GET /api/db-check

   Tries to obtain a JDBC connection from the configured DataSource
   and verifies that it is valid. If the connection is valid, information
   about the database catalog and URL is included in the response.

   On success:
   - HTTP 200 with JSON fields "status" = "UP" and "database" =
   "Connected".

   On failure:
   - HTTP 503 (SERVICE_UNAVAILABLE) with "status" = "DOWN" and an
   additional "error" message describing the issue.
Returns
[ResponseEntity<Map<String, Object>>] Database connectivity status: HTTP 200 if connected, HTTP 503 otherwise.
Definition at line 73 of file HealthController.java.
                                                             {
    Map<String, Object> response = new HashMap<>();
    try (Connection conn = dataSource.getConnection()) {
      boolean isValid = conn.isValid(2);
      if (isValid) {
        response.put("status", "UP");
        response.put("database", "Connected");
        response.put("catalog", conn.getCatalog());
        response.put("url", conn.getMetaData().getURL());
        response.put("timestamp", System.currentTimeMillis());
        return ResponseEntity.ok(response);
      } else {
        response.put("status", "DOWN");
        response.put("database", "Connection not valid");
        return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE).body(response);
      }
    } catch (Exception e) {
      response.put("status", "DOWN");
      response.put("database", "Connection failed");
      response.put("error", e.getMessage());
      response.put("timestamp", System.currentTimeMillis());
      return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE).body(response);
    }
  }
References checkDatabase(), and dataSource.
Referenced by checkDatabase().
health()
ResponseEntity< Map< String, Object > > es.ull.esit.server.controller.HealthController.health () [inline]
Basic health endpoint.
   Endpoint: GET /api/health

   Returns a small JSON payload indicating that the service is up,
   together with a timestamp and a human-readable service name.
Returns
[ResponseEntity<Map<String, Object>>] Health status with HTTP 200.
Definition at line 44 of file HealthController.java.
                                                      {
    Map<String, Object> response = new HashMap<>();
    response.put("status", "UP");
    response.put("timestamp", System.currentTimeMillis());
    response.put("service", "Restaurant Server");
    return ResponseEntity.ok(response);
  }
References health().
Referenced by health().
Member Data Documentation
dataSource
DataSource es.ull.esit.server.controller.HealthController.dataSource [private]
DataSource used to verify connectivity with the database.
Definition at line 31 of file HealthController.java.
Referenced by checkDatabase().
The documentation for this class was generated from the following file:
HealthController.java