es.ull.esit.server.controller.MainCourseController Class Reference
REST controller for managing main courses.
Public Member Functions
ResponseEntity< List< MainCourse > > getAllMainCourses ()
Returns all available main course items.
ResponseEntity< MainCourse > getMainCourseById (@PathVariable Long id)
Returns a specific main course by its ID.
ResponseEntity< MainCourse > createMainCourse (@RequestBody MainCourse mainCourse)
Creates a new main course entry.
ResponseEntity< MainCourse > updateMainCourse (@PathVariable Long id, @RequestBody MainCourse mainCourse)
Updates an existing main course entry.
ResponseEntity< Void > deleteMainCourse (@PathVariable Long id)
Deletes a main course by its ID.
Private Attributes
MainCourseRepository mainCourseRepository
Repository used to access the "main_courses" table.
Detailed Description
REST controller for managing main courses.
   Provides CRUD operations for MainCourse entities using the path
   /api/maincourses.
   These endpoints are used by the Swing client to load and modify main
   course information.
Definition at line 22 of file MainCourseController.java.
Member Function Documentation
createMainCourse()
ResponseEntity< MainCourse > es.ull.esit.server.controller.MainCourseController.createMainCourse (@RequestBody MainCourse mainCourse) [inline]
Creates a new main course entry.
   Endpoint: POST /api/maincourses
Parameters
mainCourse [MainCourse] Main course data from the request body.
Returns
[ResponseEntity<MainCourse>] The created main course with status 201
Definition at line 68 of file MainCourseController.java.
                                                                                         {
    MainCourse saved = mainCourseRepository.save(mainCourse);
    return ResponseEntity.status(HttpStatus.CREATED).body(saved);
  }
References mainCourseRepository.
deleteMainCourse()
ResponseEntity< Void > es.ull.esit.server.controller.MainCourseController.deleteMainCourse (@PathVariable Long id) [inline]
Deletes a main course by its ID.
   Endpoint: DELETE /api/maincourses/{id}
Parameters
id [Long] Identifier of the main course to delete.
Returns
[ResponseEntity<Void>] Status 204 if deleted or 404 if not found.
Definition at line 105 of file MainCourseController.java.
                                                                      {
    if (!mainCourseRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    mainCourseRepository.deleteById(id);
    return ResponseEntity.noContent().build();
  }
References deleteMainCourse(), and mainCourseRepository.
Referenced by deleteMainCourse().
getAllMainCourses()
ResponseEntity< List< MainCourse > > es.ull.esit.server.controller.MainCourseController.getAllMainCourses () [inline]
Returns all available main course items.
   Endpoint: GET /api/maincourses
Returns
[ResponseEntity<List<MainCourse>>] List of main courses with status 200.
Definition at line 37 of file MainCourseController.java.
                                                              {
    List<MainCourse> courses = mainCourseRepository.findAll();
    return ResponseEntity.ok(courses);
  }
References mainCourseRepository.
getMainCourseById()
ResponseEntity< MainCourse > es.ull.esit.server.controller.MainCourseController.getMainCourseById (@PathVariable Long id) [inline]
Returns a specific main course by its ID.
   Endpoint: GET /api/maincourses/{id}
Parameters
id [Long] Identifier of the main course.
Returns
[ResponseEntity<MainCourse>] The main course if found or 404 otherwise.
Definition at line 52 of file MainCourseController.java.
                                                                             {
    Optional<MainCourse> course = mainCourseRepository.findById(id);
    return course
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
  }
References getMainCourseById(), and mainCourseRepository.
Referenced by getMainCourseById().
updateMainCourse()
ResponseEntity< MainCourse > es.ull.esit.server.controller.MainCourseController.updateMainCourse (@PathVariable Long id, @RequestBody MainCourse mainCourse) [inline]
Updates an existing main course entry.
   Endpoint: PUT /api/maincourses/{id}
Parameters
id [Long] Identifier of the main course to update.
mainCourse [MainCourse] Updated main course data from the request body.
Returns
[ResponseEntity<MainCourse>] The updated main course if found or 404 otherwise.
Definition at line 85 of file MainCourseController.java.
                                                                                                                {
    if (!mainCourseRepository.existsById(id)) {
      return ResponseEntity.notFound().build();
    }
    mainCourse.setFoodId(id);
    MainCourse updated = mainCourseRepository.save(mainCourse);
    return ResponseEntity.ok(updated);
  }
References mainCourseRepository, and updateMainCourse().
Referenced by updateMainCourse().
Member Data Documentation
mainCourseRepository
MainCourseRepository es.ull.esit.server.controller.MainCourseController.mainCourseRepository [private]
Repository used to access the "main_courses" table.
Definition at line 26 of file MainCourseController.java.
Referenced by createMainCourse(), deleteMainCourse(), getAllMainCourses(), getMainCourseById(), and updateMainCourse().
The documentation for this class was generated from the following file:
MainCourseController.java