es.ull.esit.app.CashierLogin Class Reference
Login window for authenticating cashiers.
Public Member Functions
CashierLogin ()
Default constructor.
CashierLogin (String name)
Constructor with cashier name.
Static Public Member Functions
static void main (String[] args)
Standalone entry point for testing the Cashier window.
Private Member Functions
void updateWelcomeMessage (String name)
Updates the welcome message label.
void jButton1ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "About us" button.
void jButton2ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "Menu" button.
void jButton3ActionPerformed (java.awt.event.ActionEvent evt)
Action handler for the "LogOut" button.
void initComponents ()
Initializes GUI components.
Private Attributes
final transient ReportService reportService
Service used to retrieve reports and basic status from the backend.
javax.swing.JButton jButton1
Button that opens the "About us" information window.
javax.swing.JButton jButton2
Button that opens the general menu window (Frame1).
javax.swing.JButton jButton3
Button used to log out and return to the login screen.
javax.swing.JLabel jLabel1
Label that displays the logo or application image.
javax.swing.JPanel jPanel1
Main container panel for all UI elements.
javax.swing.JLabel welcomeTxt
Label that displays the welcome message for the cashier.
Static Private Attributes
static final String PRIMARY_FONT = "Yu Gothic UI"
static final Logger LOGGER = LoggerFactory.getLogger(CashierLogin.class)
Logger instance for logging events and errors.
static Supplier<? extends javax.swing.JFrame > cashierSupplier = () -> new CashierLogin()
Supplier for the top-level cashier window used by main(); tests can override it.
Detailed Description
Login window for authenticating cashiers.
   It is displayed after a successful login with role CASHIER.
   Shows a Swing form that lets cashiers:
   - access to the general menu window used to register orders.
   - access to the "About us" information window.
   - log out and return to the login window.

   Additionally, some actions perform background calls to the backend
   using ReportService to:
   - retrieve cashier information.
   - check the menu or system status.
Definition at line 27 of file CashierLogin.java.
Constructor & Destructor Documentation
CashierLogin() [1/2]
es.ull.esit.app.CashierLogin.CashierLogin () [inline]
Default constructor.
   Creates a cashier window without a specific name in the welcome
   message.
   Internally delegates to the constructor that accepts a name.
Definition at line 44 of file CashierLogin.java.
                        {
    this((String) null);
  }
Referenced by main().
CashierLogin() [2/2]
es.ull.esit.app.CashierLogin.CashierLogin (String name) [inline]
Constructor with cashier name.
   Creates the cashier window, initializes the GUI, builds an
   ApiClient pointing to the backend, creates a ReportService and
   updates the welcome message using the cashier name.
Parameters
name [String] Name of the cashier returned by the backend (or null for a generic welcome message).
Definition at line 58 of file CashierLogin.java.
                                   {
    initComponents();
    ApiClient client = new ApiClient("http://localhost:8080");
    this.reportService = new ReportService(client);
    updateWelcomeMessage(name);
  }
References initComponents(), and updateWelcomeMessage().
Member Function Documentation
initComponents()
void es.ull.esit.app.CashierLogin.initComponents () [inline], [private]
Initializes GUI components.
   Generated by the Form Editor: do not modify.
   Sets up the welcome label, logo image, buttons for "About us", "Menu",
   "LogOut",
   and the layout and configuration of the window.
Definition at line 372 of file CashierLogin.java.
                                {
    jPanel1 = new javax.swing.JPanel();
    welcomeTxt = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Cashier");
    setResizable(false);
    jPanel1.setBackground(new java.awt.Color(248, 244, 230));
    welcomeTxt.setFont(new java.awt.Font(PRIMARY_FONT, 1, 24)); // NOI18N
    welcomeTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    welcomeTxt.setText("Welcome Cashier");
    jButton1.setBackground(new java.awt.Color(153, 153, 153));
    jButton1.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton1.setText("About us");
    jButton1.addActionListener(this::jButton1ActionPerformed);
    jButton2.setBackground(new java.awt.Color(153, 153, 153));
    jButton2.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton2.setText("Menu");
    jButton2.addActionListener(this::jButton2ActionPerformed);
    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/screenshot.png"))); // NOI18N
    jButton3.setBackground(new java.awt.Color(255, 255, 255));
    jButton3.setFont(new java.awt.Font(PRIMARY_FONT, 1, 18)); // NOI18N
    jButton3.setText("LogOut");
    jButton3.addActionListener(this::jButton3ActionPerformed);
    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(98, 98, 98))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(183, 183, 183))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190)))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(99, 99, 99))));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                    javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(290, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(242, 242, 242))));
    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents
References initComponents(), jButton1, jButton2, jButton3, jLabel1, jPanel1, PRIMARY_FONT, and welcomeTxt.
Referenced by CashierLogin(), and initComponents().
jButton1ActionPerformed()
void es.ull.esit.app.CashierLogin.jButton1ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "About us" button.
   Action steps:
   - Starts a background thread.
   - Uses ReportService.getCashierInfo() to retrieve cashier data from
   the backend and logs the number of cashiers found.
   - Opens the Info window in the Event Dispatch Thread.
   - Closes the current Cashier window.

   Any error retrieving data is logged to the standard error stream
   but does not prevent opening the Info window.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 225 of file CashierLogin.java.
                                                                       {
    new Thread(() -> {
      try {
        List<es.ull.esit.app.middleware.model.Cashier> cashiers = reportService.getCashierInfo();
        LOGGER.info("Found {} cashiers in DB.", cashiers.size());
      } catch (Exception ex) {
        LOGGER.warn("Warning: Could not fetch cashier stats: {}", ex.getMessage());
      }
      SwingUtilities.invokeLater(() -> {
        aboutUsSupplier.get().setVisible(true);
        dispose();
      });
    }).start();
  }
References LOGGER, and reportService.
jButton2ActionPerformed()
void es.ull.esit.app.CashierLogin.jButton2ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "Menu" button.
   Action steps:
   - Starts a background thread.
   - Uses ReportService.checkMenuStatus() to verify communication
   with the backend and logs the returned status.
   - Opens the general menu window (Frame1) in the Event Dispatch
   Thread.
   - Closes the current Cashier window.

   Any error while checking the status is logged to the standard
   error stream but does not prevent opening the menu window.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 272 of file CashierLogin.java.
                                                                       {
    new Thread(() -> {
      try {
        String status = reportService.checkMenuStatus();
        LOGGER.info("Menu status: {}", status);
      } catch (Exception ex) {
        LOGGER.error("Error checking menu status: {}", ex.getMessage());
      }
      SwingUtilities.invokeLater(() -> {
        orderSupplier.get().setVisible(true);
        dispose();
      });
    }).start();
  }
References LOGGER, and reportService.
jButton3ActionPerformed()
void es.ull.esit.app.CashierLogin.jButton3ActionPerformed (java.awt.event.ActionEvent evt) [inline], [private]
Action handler for the "LogOut" button.
   Action steps:
   - Opens the Login window.
   - Closes the current Cashier window.

   Any server-side logout or token invalidation, if needed, should be
   handled outside this class.
Parameters
evt [java.awt.event.ActionEvent] Action event triggered by button click.
Definition at line 315 of file CashierLogin.java.
                                                                       {
    loginSupplier.get().setVisible(true);
    dispose();
  }
main()
void es.ull.esit.app.CashierLogin.main (String[] args) [inline], [static]
Standalone entry point for testing the Cashier window.
   Sets the Nimbus look and feel if available and shows an instance
   of Cashier without a specific cashier name. In the normal
   application flow this window is started from the Login class after
   a successful cashier login.
Parameters
args [String[]] Command line arguments (not used).
Definition at line 345 of file CashierLogin.java.
                                         {
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException
        | javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CashierLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    java.awt.EventQueue.invokeLater(() -> getCashierSupplier().get().setVisible(true));
  }
References CashierLogin().
updateWelcomeMessage()
void es.ull.esit.app.CashierLogin.updateWelcomeMessage (String name) [inline], [private]
Updates the welcome message label.
   If the name is null or empty, the label shows "Welcome Cashier".
   Otherwise the label shows "Welcome " followed by the given name.
Parameters
name [String] Cashier name or null.
Definition at line 201 of file CashierLogin.java.
                                                 {
    if (name == null || name.trim().isEmpty()) {
      welcomeTxt.setText("Welcome Cashier");
    } else {
      welcomeTxt.setText("Welcome " + name);
    }
  }
References welcomeTxt.
Referenced by CashierLogin().
Member Data Documentation
cashierSupplier
Supplier<? extends javax.swing.JFrame> es.ull.esit.app.CashierLogin.cashierSupplier = () -> new CashierLogin() [static], [private]
Supplier for the top-level cashier window used by main(); tests can override it.
Definition at line 97 of file CashierLogin.java.
jButton1
javax.swing.JButton es.ull.esit.app.CashierLogin.jButton1 [private]
Button that opens the "About us" information window.
Definition at line 476 of file CashierLogin.java.
Referenced by initComponents().
jButton2
javax.swing.JButton es.ull.esit.app.CashierLogin.jButton2 [private]
Button that opens the general menu window (Frame1).
Definition at line 478 of file CashierLogin.java.
Referenced by initComponents().
jButton3
javax.swing.JButton es.ull.esit.app.CashierLogin.jButton3 [private]
Button used to log out and return to the login screen.
Definition at line 480 of file CashierLogin.java.
Referenced by initComponents().
jLabel1
javax.swing.JLabel es.ull.esit.app.CashierLogin.jLabel1 [private]
Label that displays the logo or application image.
Definition at line 482 of file CashierLogin.java.
Referenced by initComponents().
jPanel1
javax.swing.JPanel es.ull.esit.app.CashierLogin.jPanel1 [private]
Main container panel for all UI elements.
Definition at line 484 of file CashierLogin.java.
Referenced by initComponents().
LOGGER
final Logger es.ull.esit.app.CashierLogin.LOGGER = LoggerFactory.getLogger(CashierLogin.class) [static], [private]
Logger instance for logging events and errors.
Definition at line 35 of file CashierLogin.java.
Referenced by jButton1ActionPerformed(), and jButton2ActionPerformed().
PRIMARY_FONT
final String es.ull.esit.app.CashierLogin.PRIMARY_FONT = "Yu Gothic UI" [static], [private]
Definition at line 32 of file CashierLogin.java.
Referenced by initComponents().
reportService
final transient ReportService es.ull.esit.app.CashierLogin.reportService [private]
Service used to retrieve reports and basic status from the backend.
Definition at line 30 of file CashierLogin.java.
Referenced by jButton1ActionPerformed(), and jButton2ActionPerformed().
welcomeTxt
javax.swing.JLabel es.ull.esit.app.CashierLogin.welcomeTxt [private]
Label that displays the welcome message for the cashier.
Definition at line 486 of file CashierLogin.java.
Referenced by initComponents(), and updateWelcomeMessage().
The documentation for this class was generated from the following file:
CashierLogin.java