es.ull.esit.app.middleware.service.ProductService Class Reference
Service handling business logic for menu products.
Public Member Functions
ProductService (ApiClient client)
Constructs a ProductService with the given API client.
List< Drink > getAllDrinks ()
Retrieves all drinks from the backend.
Drink getDrinkById (Long id)
Retrieves a single drink by its identifier.
void addDrink (String name, String priceStr)
Adds a new drink to the backend menu.
void updateDrink (Long id, String name, String priceStr)
Updates an existing drink in the backend menu.
List< Appetizer > getAllAppetizers ()
Retrieves all appetizers from the backend.
Appetizer getAppetizerById (Long id)
Retrieves a single appetizer by its identifier.
void addAppetizer (String name, String priceStr)
Adds a new appetizer to the backend menu.
void updateAppetizer (Long id, String name, String priceStr)
Updates an existing appetizer in the backend menu.
List< MainCourse > getAllMainCourses ()
Retrieves all main courses from the backend.
MainCourse getMainCourseById (Long id)
Retrieves a single main course by its identifier.
void addMainCourse (String name, String priceStr)
Adds a new main course to the backend menu.
void updateMainCourse (Long id, String name, String priceStr)
Updates an existing main course in the backend menu.
Private Member Functions
void validateName (String name)
Validates that the item name is not null or empty.
int validateAndParsePrice (String priceStr)
Validates and parses the price from string to integer.
Private Attributes
final ApiClient client
REST API client used to communicate with the backend menu endpoints.
Detailed Description
Service handling business logic for menu products.
   Decouples Swing UI components from direct REST API calls. It centralizes
   validation and orchestrates requests for drinks, appetizers and main
   courses.
Definition at line 16 of file ProductService.java.
Constructor & Destructor Documentation
ProductService()
es.ull.esit.app.middleware.service.ProductService.ProductService (ApiClient client) [inline]
Constructs a ProductService with the given API client.
Parameters
client [ApiClient] REST client used to perform HTTP requests.
Definition at line 26 of file ProductService.java.
                                          {
    this.client = client;
  }
References client.
Member Function Documentation
addAppetizer()
void es.ull.esit.app.middleware.service.ProductService.addAppetizer (String name, String priceStr) [inline]
Adds a new appetizer to the backend menu.
   Validates user input and sends a POST request using the ApiClient.
Parameters
name [String] Name of the new appetizer.
priceStr [String] Price entered as a string.
Definition at line 115 of file ProductService.java.
                                                         {
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    Appetizer newAppetizer = new Appetizer(null, name, price, null);
    client.createAppetizer(newAppetizer);
  }
References client, validateAndParsePrice(), and validateName().
addDrink()
void es.ull.esit.app.middleware.service.ProductService.addDrink (String name, String priceStr) [inline]
Adds a new drink to the backend menu.
   Validates the user input and sends a POST request using the ApiClient.
Parameters
name [String] Name of the new drink.
priceStr [String] Price entered as a string.
Definition at line 59 of file ProductService.java.
                                                     {
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    Drink newDrink = new Drink(null, name, price, null);
    client.createDrink(newDrink);
  }
References client, validateAndParsePrice(), and validateName().
addMainCourse()
void es.ull.esit.app.middleware.service.ProductService.addMainCourse (String name, String priceStr) [inline]
Adds a new main course to the backend menu.
   Validates user input and sends a POST request using the ApiClient.
Parameters
name [String] Name of the new main course.
priceStr [String] Price entered as a string.
Definition at line 171 of file ProductService.java.
                                                          {
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    MainCourse newMainCourse = new MainCourse(null, name, price, null);
    client.createMainCourse(newMainCourse);
  }
References client, validateAndParsePrice(), and validateName().
getAllAppetizers()
List< Appetizer > es.ull.esit.app.middleware.service.ProductService.getAllAppetizers () [inline]
Retrieves all appetizers from the backend.
Returns
[List<Appetizer>] List of all appetizers in the menu.
Definition at line 93 of file ProductService.java.
                                            {
    return client.getAllAppetizers();
  }
References client.
getAllDrinks()
List< Drink > es.ull.esit.app.middleware.service.ProductService.getAllDrinks () [inline]
Retrieves all drinks from the backend.
Returns
[List<Drink>] List of all drinks available in the menu.
Definition at line 37 of file ProductService.java.
                                    {
    return client.getAllDrinks();
  }
References client.
getAllMainCourses()
List< MainCourse > es.ull.esit.app.middleware.service.ProductService.getAllMainCourses () [inline]
Retrieves all main courses from the backend.
Returns
[List<MainCourse>] List of all main courses in the menu.
Definition at line 149 of file ProductService.java.
                                              {
    return client.getAllMainCourses();
  }
References client.
getAppetizerById()
Appetizer es.ull.esit.app.middleware.service.ProductService.getAppetizerById (Long id) [inline]
Retrieves a single appetizer by its identifier.
Parameters
id [Long] Unique identifier of the appetizer.
Returns
[Appetizer] Appetizer object corresponding to the given id.
Definition at line 103 of file ProductService.java.
                                             {
    return client.getAppetizerById(id);
  }
References client.
getDrinkById()
Drink es.ull.esit.app.middleware.service.ProductService.getDrinkById (Long id) [inline]
Retrieves a single drink by its identifier.
Parameters
id [Long] Unique identifier of the drink.
Returns
[Drink] Drink object corresponding to the given id.
Definition at line 47 of file ProductService.java.
                                     {
    return client.getDrinkById(id);
  }
References client.
getMainCourseById()
MainCourse es.ull.esit.app.middleware.service.ProductService.getMainCourseById (Long id) [inline]
Retrieves a single main course by its identifier.
Parameters
id [Long] Unique identifier of the main course.
Returns
[MainCourse] MainCourse object corresponding to the given id.
Definition at line 159 of file ProductService.java.
                                               {
    return client.getMainCourseById(id);
  }
References client.
updateAppetizer()
void es.ull.esit.app.middleware.service.ProductService.updateAppetizer (Long id, String name, String priceStr) [inline]
Updates an existing appetizer in the backend menu.
Parameters
id [Long] Identifier of the appetizer to update.
name [String] New name for the appetizer.
priceStr [String] New price entered as a string.
Definition at line 130 of file ProductService.java.
                                                                     {
    if (id == null) {
      throw new IllegalArgumentException("No appetizer selected!");
    }
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    Appetizer updatedAppetizer = new Appetizer(id, name, price, null);
    client.updateAppetizer(id, updatedAppetizer);
  }
References client, validateAndParsePrice(), and validateName().
updateDrink()
void es.ull.esit.app.middleware.service.ProductService.updateDrink (Long id, String name, String priceStr) [inline]
Updates an existing drink in the backend menu.
Parameters
id [Long] Identifier of the drink to update.
name [String] New name for the drink.
priceStr [String] New price entered as a string.
Definition at line 74 of file ProductService.java.
                                                                 {
    if (id == null) {
      throw new IllegalArgumentException("No drink selected!");
    }
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    Drink updatedDrink = new Drink(id, name, price, null);
    client.updateDrink(id, updatedDrink);
  }
References client, validateAndParsePrice(), and validateName().
updateMainCourse()
void es.ull.esit.app.middleware.service.ProductService.updateMainCourse (Long id, String name, String priceStr) [inline]
Updates an existing main course in the backend menu.
Parameters
id [Long] Identifier of the main course to update.
name [String] New name for the main course.
priceStr [String] New price entered as a string.
Definition at line 186 of file ProductService.java.
                                                                      {
    if (id == null) {
      throw new IllegalArgumentException("No main course selected!");
    }
    int price = validateAndParsePrice(priceStr);
    validateName(name);
    MainCourse updatedMainCourse = new MainCourse(id, name, price, null);
    client.updateMainCourse(id, updatedMainCourse);
  }
References client, validateAndParsePrice(), and validateName().
validateAndParsePrice()
int es.ull.esit.app.middleware.service.ProductService.validateAndParsePrice (String priceStr) [inline], [private]
Validates and parses the price from string to integer.
   Ensures the price is a non-negative integer value.
Parameters
priceStr [String] Price entered as a string.
Returns
[int] Parsed price value.
Exceptions
IllegalArgumentException If the price is empty, negative or not a valid number.
Definition at line 221 of file ProductService.java.
                                                     {
    if (priceStr == null || priceStr.trim().isEmpty()) {
      throw new IllegalArgumentException("Price cannot be empty.");
    }
    try {
      int price = Integer.parseInt(priceStr.trim());
      if (price < 0) {
        throw new IllegalArgumentException("Price cannot be negative.");
      }
      return price;
    } catch (NumberFormatException e) {
      throw new IllegalArgumentException("Price must be a valid whole number.");
    }
  }
Referenced by addAppetizer(), addDrink(), addMainCourse(), updateAppetizer(), updateDrink(), and updateMainCourse().
validateName()
void es.ull.esit.app.middleware.service.ProductService.validateName (String name) [inline], [private]
Validates that the item name is not null or empty.
Parameters
name [String] Name of the item to validate.
Exceptions
IllegalArgumentException If the name is null or empty.
Definition at line 206 of file ProductService.java.
                                         {
    if (name == null || name.trim().isEmpty()) {
      throw new IllegalArgumentException("Item name cannot be empty.");
    }
  }
Referenced by addAppetizer(), addDrink(), addMainCourse(), updateAppetizer(), updateDrink(), and updateMainCourse().
Member Data Documentation
client
final ApiClient es.ull.esit.app.middleware.service.ProductService.client [private]
REST API client used to communicate with the backend menu endpoints.
Definition at line 19 of file ProductService.java.
Referenced by addAppetizer(), addDrink(), addMainCourse(), getAllAppetizers(), getAllDrinks(), getAllMainCourses(), getAppetizerById(), getDrinkById(), getMainCourseById(), ProductService(), updateAppetizer(), updateDrink(), and updateMainCourse().
The documentation for this class was generated from the following file:
ProductService.java