es.ull.esit.app.middleware.model.User Class Reference
Client-side model representing an authenticated user.
Public Member Functions
User ()
Default constructor required for JSON deserialization.
User (String username, String role)
Constructs a user with the given username and role.
String getUsername ()
Gets the username.
void setUsername (String username)
Sets the username.
String getRole ()
Gets the user role.
void setRole (String role)
Sets the user role.
boolean isAdmin ()
Checks if the user has the ADMIN role.
Private Attributes
String username
Username of the authenticated user (JSON property "username").
String role
Role of the user (JSON property "role"), e.g., ADMIN or CASHIER.
Detailed Description
Client-side model representing an authenticated user.
   It maps the JSON returned by the "/api/login" endpoint and contains
   only the fields needed by the Swing application: username and role.
Definition at line 13 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
Constructor & Destructor Documentation
User() [1/2]
es.ull.esit.app.middleware.model.User.User () [inline]
Default constructor required for JSON deserialization.
Definition at line 26 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                {
  }
References User().
Referenced by User().
User() [2/2]
es.ull.esit.app.middleware.model.User.User (String username, String role) [inline]
Constructs a user with the given username and role.
Parameters
username [String] Username of the user.
role [String] Role of the user.
Definition at line 35 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                                            {
    this.username = username;
    this.role = role;
  }
References role, and username.
Member Function Documentation
getRole()
String es.ull.esit.app.middleware.model.User.getRole () [inline]
Gets the user role.
Returns
[String] Role of the user.
Definition at line 63 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                          {
    return role;
  }
References role.
Referenced by es.ull.esit.app.Login.jButton1ActionPerformed().
getUsername()
String es.ull.esit.app.middleware.model.User.getUsername () [inline]
Gets the username.
Returns
[String] Username of the user.
Definition at line 45 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                              {
    return username;
  }
References username.
Referenced by es.ull.esit.app.Login.jButton1ActionPerformed().
isAdmin()
boolean es.ull.esit.app.middleware.model.User.isAdmin () [inline]
Checks if the user has the ADMIN role.
Returns
[boolean] True if the user role is ADMIN (case-insensitive), false otherwise.
Definition at line 81 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                           {
    return "ADMIN".equalsIgnoreCase(this.role);
  }
References role.
setRole()
void es.ull.esit.app.middleware.model.User.setRole (String role) [inline]
Sets the user role.
Parameters
role [String] Role of the user.
Definition at line 72 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                                   {
    this.role = role;
  }
References role.
setUsername()
void es.ull.esit.app.middleware.model.User.setUsername (String username) [inline]
Sets the username.
Parameters
username [String] Username of the user.
Definition at line 54 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
                                           {
    this.username = username;
  }
References username.
Member Data Documentation
role
String es.ull.esit.app.middleware.model.User.role [private]
Role of the user (JSON property "role"), e.g., ADMIN or CASHIER.
Definition at line 21 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
Referenced by getRole(), isAdmin(), setRole(), and User().
username
String es.ull.esit.app.middleware.model.User.username [private]
Username of the authenticated user (JSON property "username").
Definition at line 17 of file src/main/java/es/ull/esit/app/middleware/model/User.java.
Referenced by getUsername(), setUsername(), and User().
The documentation for this class was generated from the following file:
src/main/java/es/ull/esit/app/middleware/model/User.java