es.ull.esit.server.controller.CashierController Class Reference
REST controller for managing cashiers.
Public Member Functions
ResponseEntity< List< Cashier > > getAllCashiers ()
Returns all cashiers.
ResponseEntity< Cashier > getCashierById (@PathVariable Long id)
Returns a single cashier by ID.
ResponseEntity< Cashier > getCashierByName (@PathVariable String name)
Returns a single cashier by name (username).
ResponseEntity< Cashier > updateCashier (@PathVariable Long id, @RequestBody Cashier cashier)
Updates an existing cashier, but only the name and salary fields.
Private Attributes
CashierRepository cashierRepository
Detailed Description
REST controller for managing cashiers.
   Provides CRUD operations for Cashier entities using the path
   "/api/cashiers".

   Cashiers are created automatically when users with 'CASHIER' role are
   added to the table 'users'.
   This controller is mainly READ-ONLY and allows updating salary/name.
Definition at line 25 of file CashierController.java.
Member Function Documentation
getAllCashiers()
ResponseEntity< List< Cashier > > es.ull.esit.server.controller.CashierController.getAllCashiers () [inline]
Returns all cashiers.
   HTTP GET /api/cashiers
Returns
[ResponseEntity<List<Cashier>>] List of cashiers with HTTP 200 status.
Definition at line 40 of file CashierController.java.
                                                        {
    List<Cashier> cashiers = cashierRepository.findAll();
    return ResponseEntity.ok(cashiers);
  }
References cashierRepository.
getCashierById()
ResponseEntity< Cashier > es.ull.esit.server.controller.CashierController.getCashierById (@PathVariable Long id) [inline]
Returns a single cashier by ID.
   HTTP GET /api/cashiers/{id}
Parameters
id [Long] Identifier of the cashier.
Returns
[ResponseEntity<Cashier>] The cashier if found with HTTP 200 status, or HTTP 404 if not found.
Definition at line 55 of file CashierController.java.
                                                                       {
    Optional<Cashier> cashier = cashierRepository.findById(id);
    return cashier
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
  }
References cashierRepository, and getCashierById().
Referenced by getCashierById().
getCashierByName()
ResponseEntity< Cashier > es.ull.esit.server.controller.CashierController.getCashierByName (@PathVariable String name) [inline]
Returns a single cashier by name (username).
   HTTP GET /api/cashiers/name/{name}
Parameters
name [String] Name of the cashier.
Returns
[ResponseEntity<Cashier>] The cashier if found with HTTP 200 status, or HTTP 404 if not found.
Definition at line 72 of file CashierController.java.
                                                                             {
    Optional<Cashier> cashier = cashierRepository.findByName(name);
    return cashier
        .map(ResponseEntity::ok)
        .orElseGet(() -> ResponseEntity.notFound().build());
  }
References cashierRepository, and getCashierByName().
Referenced by getCashierByName().
updateCashier()
ResponseEntity< Cashier > es.ull.esit.server.controller.CashierController.updateCashier (@PathVariable Long id, @RequestBody Cashier cashier) [inline]
Updates an existing cashier, but only the name and salary fields.
   HTTP PUT /api/cashiers/{id}
Parameters
id [Long] Identifier of the cashier to update.
cashier [Cashier] New data for the cashier.
Returns
[ResponseEntity<Cashier>] The updated cashier with HTTP 200 status, or HTTP 404 if not found.
Definition at line 90 of file CashierController.java.
                                    {
    Optional<Cashier> existingOpt = cashierRepository.findById(id);
    if (!existingOpt.isPresent()) {
      return ResponseEntity.notFound().build();
    }
    Cashier existing = existingOpt.get();
    existing.setName(cashier.getName());
    existing.setSalary(cashier.getSalary());
    Cashier updated = cashierRepository.save(existing);
    return ResponseEntity.ok(updated);
  }
References cashierRepository, es.ull.esit.server.middleware.model.Cashier.setName(), and updateCashier().
Referenced by updateCashier().
Member Data Documentation
cashierRepository
CashierRepository es.ull.esit.server.controller.CashierController.cashierRepository [private]
Definition at line 29 of file CashierController.java.
Referenced by getAllCashiers(), getCashierById(), getCashierByName(), and updateCashier().
The documentation for this class was generated from the following file:
CashierController.java